pub const HELP: &[(&str, &str)] = &[
    ("j / k", "move selection"),
    ("J / K", "reorder selected task"),
    ("h / l  or  ← / →", "previous / next day"),
    ("Space", "start or stop timer (JIRA → In Progress / To Do)"),
    ("n", "new task"),
    ("e", "edit task (label, description, time, status, code, notes, tags, link, flags)"),
    ("s / Enter", "on the status field: pick from the status list"),
    ("p/i/a/c/x/d", "on the flags field: toggle pinned/important/archived/cancelled/deleted/completed"),
    ("i", "task detail view (comments, PRs, commit status)"),
    ("C", "task comments (n to write one)"),
    ("d", "delete task"),
    ("D", "toggle done (JIRA → Cek di Local)"),
    ("r", "reset selected timer"),
    ("R", "reset all timers today"),
    ("m", "toggle focus / parallel"),
    ("x", "export markdown report to clipboard"),
    ("?", "this help"),
    ("a", "toggle daily \u{2194} archive"),
    ("/", "filter archive by label"),
    ("t", "filter archive by tag"),
    ("s", "filter archive by status (id or name)"),
    ("g", "filter archive by integration substring"),
    ("c", "continue archive task today"),
    ("q", "quit"),
    ("Ctrl+J", "JIRA menu (comment, transition, sprint picker)"),
    ("Ctrl+J 3", "sprint picker: unassigned / reporter / assignee undone, or fetch by key"),
    ("Ctrl+B", "git menu (link branch, commits, PR status, import PR comments)"),
    ("Esc", "close overlay / cancel"),
    ("Tab", "next field in form"),
    ("Enter", "save form"),
];
